### ISSUE TITLE
bad behaviour of contextmenu callback for geoJSON layer objects

### ISSUE THREAD

**Issue by jdembdr** [aratcliffe/Leaflet.contextmenu#39]
Hi,
I try to give different link on a contextmenu depending of which JSON element was right clicked.
Here is a fiddle for this bug: 
http://jsfiddle.net/jdembdr/y97k2n2z/embedded/result/

The same property (name 'A') appears in my callback for every element when I try to initialize a contextmenu during the onEachFeature processing of the  GeoJSON layer building step.
```javascript
var controlLayer = L.control.layers();
controlLayer.addOverlay(L.geoJson(docks_json, {onEachFeature: addContextLayer}),'Docks');
```
```javascript
function addContextLayer(feature, layer) {
    if (feature.properties && feature.properties.name) {
		var contextMenuItems = [{
        	text: 'dock name',
        	callback: function(e){alert(feature.properties.name)},
    	},];
    	this["contextmenu"]=true;
        this["contextmenuItems"]=contextMenuItems;
        this["contextmenuInheritItems"]=false;
	}
}
```

ie . **feature.properties.name** is the same for every element when callback is called.

I don't know very well JS so maybe is it just a misunderstanding of the langage, but if you could help me, It would be great !

**Comment by jdembdr** [comment]
I've already tried to make working solution proposed fot bug https://github.com/aratcliffe/Leaflet.contextmenu/issues/12.
However, I think I'm doing everything wrong.

Could you confirm me that with your API, a contextmenu can only be attached to a map, a marker or a layer and can't be different for all polygons of a GeoJSON layer ?
```javascript
function addContextLayer(feature, layer) {
     if (feature.properties && feature.properties.name) {
         var marker;
         marker = new L.Marker([43.12, 5.34], {
             title: feature.properties.name,
             contextmenu: true,
             contextmenuItems: [{
                 text: 'dock ' + feature.properties.name,
                 callback: function (e) {
                     alert(feature.properties.id);
                 },
                 context:feature,
          
             }, {
                 separator: true,
                 index: 1
             }]
         });
         marker.addTo(layer);
     }
 }
```

If so, a solution would be to create a marker for each polygon and attach a contextmenu on it.
Do you agree ? Do you know an another solution ?

**Comment by aratcliffe** [comment]
Hi, the context menu mixin supports showing/hiding the context menu on L.Marker and L.Path layer types. It adds a bindContextMenu() method to these types which accepts the context menu options. It's this method you need to use in the onEachFeature callback.

I was looking at your fiddle and you were attempting to set the context menu options on the L.GeoJSON layer itself, this meant that with each invocation of the callback you were simply overwriting the options and explains why you saw the same property displayed when clicking the context menu item - it was the value for the last feature the callback was invoked for.

The layer object passed to the callback refers to a L.FeatureGroup not an L.Path type, probably because your GeoJSON data contains multipolygon data, thus you need to call bindContextMenu() on each of the group's features.  The re-written callback looks like this:

````javascript
function addContextLayer(feature, layer) {
    if (feature.properties && feature.properties.name) {
		var contextMenuItems = [{
        	text: 'dock name',
        	callback: function(e){alert(feature.properties.name)},
    	},];
        
        layer.eachLayer(function (l) {
            l.bindContextMenu({
                contextmenu: true,
                contextmenuItems: contextMenuItems
            });
        });
	}
}
````

**Comment by jdembdr** [comment]
Thank you !
It works perfectly, as expected. I close this issue.
