### ISSUE TITLE
Could you change the minified file name?

### ISSUE THREAD

**Issue by kennynaoh** [aratcliffe/Leaflet.contextmenu#52]
Hello @aratcliffe ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a problem.
The minified file in your library is ```leaflet.contextmenu.js```.
Could change the file name consist of ```"min"```, like ```leaflet.contextmenu-src.min.js``` or the other?
Thanks.

https://github.com/cdnjs/cdnjs/issues/7827
https://github.com/cdnjs/cdnjs/pull/7836

**Comment by PeterDaveHello** [comment]
> The minified file in your library is leaflet.contextmenu.js.

This is not the "problem".

The problem is, the js file has a minified release, but the css file doesn't, so that we need to manually minify it, the most common naming policy is `name.ext` -> `name.min.ext`, so we'll minify `leaflet.contextmenu.css` to `leaflet.contextmenu.min.css`, so the js file and css file will have different naming policy, another problem is that we want to apply auto-update on all the libs, so that once you release a new version, we'll get it very soon, but the auto-update process can not recognize the mixed  naming schem, so that it can not automatically minify and publish the new versions, which means we can not use auto-update on it.

I'll respectfully suggest you consider to also provide the minified css file, no matter what's the naming schem, since there is already minified file, so that we don't need to manually minify the project, then the naming isn't that important, another way is to change the filename of `leaflet.contextmenu.js`, name the source file `leaflet.contextmenu.js` and the minified file `leaflet.contextmenu.min.js`, so the naming will be consistent, the automatically minify process can easily handle it.

Thanks a lot!
Peter

**Comment by aratcliffe** [comment]
I've added a compressed stylesheet and renamed the files to fit with the cdnjs conventions.
