### ISSUE TITLE
Attach Context Menu after loading polygon

### ISSUE THREAD

**Issue by boniyustin** [aratcliffe/Leaflet.contextmenu#54]
Is it possible to attach context menu after we load the polygon? 
Because I need to set the title and function after i know the location(longitude,latitude) of the click event

**Comment by aratcliffe** [comment]
Hi, sorry for the late reply. In most cases you shouldn't need to attach the context menu after the polygon has loaded because the show event object gives you a reference to the polygon through which you can access the polygon properties. For example:

````
map.on('contextmenu.show', function (event) {
         var marker = event.relatedTarget;
         // do something with your marker
});
````

However the mixin provides you with methods for binding and unbinding the context menu to the map after a feature has been created. See [https://github.com/aratcliffe/Leaflet.contextmenu#mixin-methods](https://github.com/aratcliffe/Leaflet.contextmenu#mixin-methods)
